server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/campus_notify?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ***REMOVED***
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
