server:
  port: 8087

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/campus_settlement?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ***REMOVED***
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
      password: ***REMOVED***
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
