server:
  port: 8092

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/campus_review?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ***REMOVED***
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoints:
    web:
      exposure:
        include: health,info
