server:
  port: 8093

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/campus_file?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ***REMOVED***
    type: com.alibaba.druid.pool.DruidDataSource

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: campus-file

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
