canal.instance.mysql.slaveId=1234
canal.instance.master.address=host.docker.internal:3307
canal.instance.dbUsername=root
canal.instance.dbPassword=${DB_PASSWORD}
canal.instance.defaultDatabaseName=campus_product
canal.instance.filter.regex=campus_product\..*
canal.mq.topic=canal.data.sync.key
